### ISSUE TITLE
I can see a list of all sports

### ISSUE THREAD

**Issue by Kevinwey** [Kevinwey/Lotr-App#4]
### **Value Proposition**
<hr>

**As a** User
**I want to** see a list of all sports
**so that** I have an overview of all sports

### **Description**
<hr>

![Image](https://user-images.githubusercontent.com/123939438/229359577-ab6ce10d-2d88-4c91-8b97-76c357bd37f2.png)

### **Acceptance Criteria**
<hr>

- [ ] all events are displayed in a list
- [ ] the list should have a headline
- [ ] sorted by name

### **Tasks**

- [ ] create dummy data
- [ ] fetch the dummy data and displayed it in a list
- [ ] write tests
